gpn-prototypes/vega-sp

- jest.config.js
- src/App.tsx
- src/pages/projects/ProjectsPage.css
- src/pages/projects/ProjectsPage.test.tsx
- src/pages/projects/ProjectsPage.tsx
- src/pages/projects/cn-projects-page.ts
- src/pages/projects/index.ts
Задача в Jira: https://jira.csssr.io/browse/VEGA-133
Ссылка на стенд: https://VEGA-133.vega-2.csssr.cloud
> VEGA-133: Страница «Проекты»: создать страницу в роутинге и лэйаут

- .github/CODEOWNERS
Задача в Jira: https://jira.csssr.io/browse/VEGA-220
Ссылка на стенд: https://VEGA-220.vega-2.csssr.cloud
Jira issue: VEGA-220
> VEGA-220 добавить codeowner

- src/components/ProjectForm/ProjectForm.css
- src/components/ProjectForm/steps/Step2.tsx
- src/pages/auth/AuthPage.css
- src/pages/auth/AuthPage.tsx
- src/pages/create-project/CreateProjectPage.tsx
Задача в Jira: https://jira.csssr.io/browse/VEGA-260
Ссылка на стенд: https://VEGA-260.vega-2.csssr.cloud
> VEGA-260: Подготовка к демо (подчистить макеты)

- src/ui/features/auth/AuthForm/AuthForm.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-360
Ссылка на стенд: http://VEGA-360.vega-2.csssr.cloud
> VEGA-360: Исправить верстку на странице авторизации

- package.json
- setup-tests.ts
- src/App/App.css
- src/App/App.tsx
- src/App/AppView.tsx
- src/App/index.tsx
- src/pages/create-project/CreateProjectPage.tsx
- webpack.forShellConfig.js
- yarn.lock
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-499
Ссылка на стенд: http://VEGA-499.vega-2.csssr.cloud
Jira issue: VEGA-438
> VEGA-499: Прикрутить apollo к vega-sp

- codegen.yml
- graphql.schema.json
- package.json
- schema.graphql
- src/data/projects/index.ts
- src/data/projects/query.ts
- src/generated/graphql.tsx
- src/layouts/DataLayout/DataLayout.tsx
- src/layouts/DataLayout/index.ts
- src/pages/projects/ProjectsPage.tsx
- src/pages/projects/ProjectsPageView.test.tsx
- src/pages/projects/ProjectsPageView.tsx
- yarn.lock
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-483
Ссылка на стенд: http://VEGA-483.vega-2.csssr.cloud
Jira issue: VEGA-483
> VEGA-483:  [BACK INTEGR] Интегрироваться с бэком в части списка проектов

- src/App/AppView.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-440
Ссылка на стенд: http://VEGA-440.vega-2.csssr.cloud
Jira issue: VEGA-440
> VEGA-440: Интегрировать vega-sp с vega-shell

- .github/kuberta.yaml
- .github/workflows/build-static.yaml
- package.json
- webpack.forShellConfig.js
- yarn.lock
> VEGA-439: Настроить деплой vega-sp

- .eslintrc.js
- src/App/index.tsx
- src/pages/create-project/CreateProjectPage.tsx
- src/pages/create-project/create-project.graphql
- src/pages/create-project/types.ts
- src/pages/projects/ProjectsPage.tsx
- src/pages/projects/ProjectsPageView.tsx
- src/ui/core/TextField/TextField.tsx
- src/ui/features/projects/ProjectForm/ProjectForm.tsx
- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-222
Ссылка на стенд: http://VEGA-222.vega-2.csssr.cloud
> VEGA-222: Интеграция с бэком "Создание проекта"

- .github/workflows/update-pr.yml
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-512
Ссылка на скрипт: http://VEGA-512.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-512
> Добавить ссылку на скрипт

- src/pages/projects/ProjectsPageView.tsx
- src/pages/projects/ProjectsTable/ProjectsTable.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-134
Ссылка на скрипт: http://VEGA-134.vega-sp.csssr.cloud/vega-sp.js
> VEGA-134: Страница «Проекты»: собрать страницу из готовых компонентов

- package.json
- src/pages/projects/ProjectsPageView.tsx
- src/pages/projects/ProjectsTable/ProjectsTable.tsx
- yarn.lock
> Обновление версии vega-ui

- src/pages/project/project.graphql
- src/ui/features/projects/ProjectForm/ProjectForm.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-615
Ссылка на скрипт: http://VEGA-615.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-615
> VEGA-615: Исправить схему после обновления

- package.json
- webpack.config.js
- webpack.forShellConfig.js
- yarn.lock
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-504
Ссылка на скрипт: http://VEGA-504.vega-sp.csssr.cloud/vega-sp.js
> VEGA-504: Настроить сборку общих зависимостей в vega-shell

- package.json
- webpack.forShellConfig.js
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-505
Ссылка на скрипт: http://VEGA-505.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-505
> VEGA-505: Разобраться с подключением vega-ui в обвязке

- src/pages/projects/ProjectsPage.css
- src/pages/projects/ProjectsPage.tsx
- src/pages/projects/ProjectsPageView.test.tsx
- src/pages/projects/ProjectsPageView.tsx
- src/pages/projects/ProjectsTable/EditedAt/EditedAt.css
- src/pages/projects/ProjectsTable/EditedAt/EditedAt.tsx
- src/pages/projects/ProjectsTable/EditedAt/index.ts
- src/pages/projects/ProjectsTable/ProjectsTable.css
- src/pages/projects/ProjectsTable/ProjectsTable.tsx
- src/pages/projects/ProjectsTable/index.ts
- src/pages/projects/ProjectsTable/types.ts
- src/pages/projects/projects.graphql
- src/pages/projects/use-snackbar.ts
- yarn.lock
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-551
Ссылка на скрипт: http://VEGA-551.vega-sp.csssr.cloud/vega-sp.js
> VEGA-551: Редактирование и удаление проекта в таблице

- src/App/App.css
- src/App/AppView.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-613
Ссылка на скрипт: http://VEGA-613.vega-sp.csssr.cloud/vega-sp.js
> VEGA-613: Исправить конфликты стилей

- src/pages/projects/ProjectsPage.tsx
- src/pages/projects/ProjectsPageView.test.tsx
- src/pages/projects/ProjectsPageView.tsx
- src/pages/projects/ProjectsTable/ProjectsTable.tsx
- src/pages/projects/ProjectsTable/types.ts
- src/pages/projects/projects.graphql
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-547
Ссылка на скрипт: http://VEGA-547.vega-sp.csssr.cloud/vega-sp.js
> VEGA-547: Добавить в избранное. Интеграция с бэком

- src/pages/projects/ProjectsFilter/ProjectsFilter.tsx
- src/pages/projects/ProjectsFilter/index.ts
- src/pages/projects/ProjectsPage.css
- src/pages/projects/ProjectsPage.tsx
- src/pages/projects/ProjectsPageView.tsx
- src/pages/projects/ProjectsTable/EditedAt/EditedAt.css
- src/pages/projects/ProjectsTable/EditedAt/EditedAt.tsx
- src/pages/projects/ProjectsTable/ProjectsTable.css
- src/pages/projects/ProjectsTable/ProjectsTable.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-599
Ссылка на скрипт: http://VEGA-599.vega-sp.csssr.cloud/vega-sp.js
> VEGA-599: Изменить таблицу на странице списка проектов

- package.json
- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
- yarn.lock
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-578
Ссылка на скрипт: http://VEGA-578.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-407
> Обновить версию gpn-prototypes/vega-ui

- webpack.forShellConfig.js
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-630
Ссылка на скрипт: http://VEGA-630.vega-sp.csssr.cloud/vega-sp.js
> VEGA-630: Прокинуть переменные окружения в сборку

- src/pages/project/project.graphql
- src/ui/features/projects/ProjectForm/Footer.tsx
- src/ui/features/projects/ProjectForm/ProjectForm.tsx
- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-578
Ссылка на скрипт: http://VEGA-578.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-578
Обновил схему
Добавил генерацию для списка лет
Добавил кнопку отмены для редактирования
> Добавление мелких правок

- src/pages/projects/ProjectsPage.tsx
- src/pages/projects/ProjectsPageView.tsx
- src/pages/projects/ProjectsTable/ProjectsTable.css
- src/pages/projects/ProjectsTable/ProjectsTable.tsx
- src/pages/projects/ProjectsTable/types.ts
- src/pages/projects/projects.graphql
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-638
Ссылка на скрипт: http://VEGA-638.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-638
> VEGA-638: Реализовать отображение описания проекта

- src/ui/features/projects/ProjectForm/ProjectForm.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-643
Ссылка на скрипт: http://VEGA-643.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-643
> VEGA-643: Исправить область навигации на странице создания проекта

- src/pages/projects/ProjectsPage.css
- src/pages/projects/ProjectsPage.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-631
Ссылка на скрипт: http://VEGA-631.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-631
> VEGA-631: Изменить компонент уведомления об удалении проекта

- src/pages/project/CreateProjectPage.tsx
- src/pages/project/EditProjectPage.tsx
- src/ui/features/projects/ProjectForm/Banner.tsx
- src/ui/features/projects/ProjectForm/ProjectForm.tsx
- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
Не добавляйте задачу в релиз. Нужно дождаться аппрува от дизайнера
> VEGA-646: Исправить возможность добавлять кастомное значение в поле Регион

- src/pages/project/CreateProjectPage.tsx
- src/pages/projects/ProjectsPage.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-642
Ссылка на скрипт: http://VEGA-642.vega-sp.csssr.cloud/vega-sp.js
> VEGA-642: Добавить негативные уведомления на страницы

- src/providers/snackbar/Snackbar.css
- src/providers/snackbar/Snackbar.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-659
Ссылка на скрипт: http://VEGA-659.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-659
> VEGA-659: Исправить взаимодействие с кнопками футера при наличии уведомления

- src/App/App.css
- src/layouts/PageLayout/PageLayout.css
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-637
Ссылка на скрипт: http://VEGA-637.vega-sp.csssr.cloud/vega-sp.js
> fix(css): убрать вертикальную прокрутку

- src/ui/features/projects/ProjectForm/ProjectForm.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-677
Ссылка на скрипт: http://VEGA-677.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-677
> VEGA-677: Исправить моргание контента на странице редактирования проекта

- src/App/App.css
- src/layouts/PageLayout/PageLayout.css
- src/pages/projects/ProjectsPage.css
> VEGA-682: Фикс контейнера для vega-sp

- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-697
Ссылка на скрипт: http://VEGA-697.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-697
> VEGA-697: [В МАСТЕР] Исправить поведение списка Регион при выборе значения после скролла

- codegen.yml
- src/pages/project/CreateProjectPage.tsx
- src/pages/project/EditProjectPage.tsx
- src/pages/project/project.graphql
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-700
Ссылка на скрипт: http://VEGA-700.vega-sp.csssr.cloud/vega-sp.js
- удалено поле type
- изменен стенд для получения схемы
> VEGA-700: [В МАСТЕР] Невозможно создать проект

- .github/workflows/build-static.yaml
- .github/workflows/continuous-integration.yml
- codegen.yml
> fix(codegen): получать url и переменных окружения

- app-config/index.js
- src/App/index.tsx
- webpack.forShellConfig.js
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-719
Ссылка на скрипт: http://VEGA-719.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-719
> VEGA-719: Избавиться от упоминаний стендов в репозиториях

- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-662
Ссылка на скрипт: http://VEGA-662.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-662
> VEGA-662: Убрать автозаполнение поля Название проекта

- src/ui/features/projects/ProjectForm/Banner.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-684
Ссылка на скрипт: http://VEGA-684.vega-sp.csssr.cloud/vega-sp.js
> VEGA-684: Восстановить отображение наименования проекта и региона в баннере страниц создания и редактирования

- src/App/App.tsx
- src/App/AppView.tsx
- src/App/index.tsx
- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-672
Ссылка на скрипт: http://VEGA-672.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-672
> VEGA-672: Заменить роутер в vega-shell

- package.json
- yarn.lock
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-728
Ссылка на скрипт: http://VEGA-728.vega-sp.csssr.cloud/vega-sp.js
Обновлена версия vega-ui
> VEGA-728: Избавить от дублирования стилей vega-ui

- src/pages/project/CreateProjectPage.tsx
- src/pages/project/EditProjectPage.tsx
- src/pages/project/ProjectPage.css
- src/pages/project/RouteLeavingGuard.tsx
- src/pages/project/project.graphql
- src/ui/features/projects/ProjectForm/ProjectForm.tsx
- src/ui/features/projects/ProjectForm/types.ts
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-586
Ссылка на скрипт: http://VEGA-586.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-586
> VEGA-586: Реализовать механизм отмены создания проекта

- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
- yarn.lock
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-681
Ссылка на скрипт: http://VEGA-681.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-681
> VEGA-681: Доработать форму создания проекта - добавить комбобокс

- src/pages/project/CreateProjectPage.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-736
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-723
Ссылка на скрипт: http://VEGA-736.vega-sp.csssr.cloud/vega-sp.js
> VEGA-736: Изменить логику работы с черновиком

- .graphqlrc.yaml
- codegen.yml
- package.json
- src/pages/project/CreateProjectPage.tsx
- src/pages/project/EditProjectPage.tsx
- src/pages/project/project.graphql
- src/pages/project/types.ts
- src/pages/projects/ProjectsPage.tsx
- src/pages/projects/ProjectsPageView.tsx
- src/pages/projects/ProjectsTable/ProjectsTable.tsx
- src/pages/projects/projects.graphql
- src/ui/features/projects/ProjectForm/ProjectForm.tsx
- src/ui/features/projects/ProjectForm/index.ts
- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
- src/ui/features/projects/ProjectForm/types.ts
- yarn.lock
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-515
Ссылка на скрипт: http://VEGA-515.vega-sp.csssr.cloud/vega-sp.js
https://github.com/gpn-prototypes/vega-shell/pull/64
> VEGA-515: Интегрировать сервис для решения конфликтов в обвязку

- src/pages/project/CreateProjectPage.tsx
- src/pages/project/EditProjectPage.tsx
- src/ui/features/projects/ProjectForm/ProjectForm.css
- src/ui/features/projects/ProjectForm/ProjectForm.tsx
- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
- src/ui/forms/validation/validate-form.test.ts
- src/ui/forms/validation/validators/validators.ts
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-577
Ссылка на скрипт: http://VEGA-577.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-577
> VEGA-577: Добавить валидацию к полям вкладки Описание проекта

- src/pages/project/EditProjectPage.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-760
Ссылка на скрипт: http://VEGA-760.vega-sp.csssr.cloud/vega-sp.js
> VEGA-760: Убрать доп. уведомление Проект не найден на странице 404

- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
> fix: исправить типы в форме проекта

- src/hooks/index.ts
- src/hooks/use-browser-tab-activity.ts
- src/pages/project/EditProjectPage.tsx
- src/pages/projects/ProjectsPage.tsx
- src/ui/features/projects/ProjectForm/ProjectForm.tsx
- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
- src/ui/features/projects/ProjectForm/types.ts
- src/ui/forms/validation/validate-form.test.ts
- src/ui/forms/validation/validators/validators.ts
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-765
Ссылка на скрипт: http://VEGA-765.vega-sp.csssr.cloud/vega-sp.js
- исправил баг с автообновлением
- добавил синхронизацию данных таблицы и формы через поллинг и перезапрос по активности вкладки
> VEGA-765: Исправить автообновление формы

- package.json
- src/pages/project/ProjectPage.css
- src/pages/project/RouteLeavingGuard.tsx
- src/pages/projects/ProjectsPage.css
- src/pages/projects/ProjectsPage.tsx
- yarn.lock
Задача в Jira CSSSR: 
- https://jira.csssr.io/browse/VEGA-724
- https://jira.csssr.io/browse/VEGA-699
- https://jira.csssr.io/browse/VEGA-749
Ссылка на скрипт: http://VEGA-724.vega-sp.csssr.cloud/vega-sp.js
> VEGA-724: Исправить расположение уведомления Удалить проект при длинном списке проекта

- src/ui/features/projects/ProjectForm/ProjectForm.tsx
- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-766
Ссылка на скрипт: http://VEGA-766.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-766
> VEGA-766: Добавить ограничение на поле Описание проекта

- src/pages/project/CreateProjectPage.tsx
- src/pages/project/EditProjectPage.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-762
Ссылка на скрипт: http://VEGA-762.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-762
> VEGA-762: Восстановить крестик у системных красных уведомлений

- src/ui/features/projects/ProjectForm/ProjectForm.tsx
- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-767
Ссылка на скрипт: http://VEGA-767.vega-sp.csssr.cloud/vega-sp.js
> VEGA-767: Исправить валидацию на поле Год начала планирования, если введено менее 4 символов

- src/pages/projects/ProjectsPage.css
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-721
Ссылка на скрипт: http://VEGA-721.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-721
> VEGA-721: Поменять цвет фона в списке проектов

- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
- src/ui/forms/validation/validators/validators.ts
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-770
Ссылка на скрипт: http://VEGA-770.vega-sp.csssr.cloud/vega-sp.js
> VEGA-770: Исправить валидацию года

- src/ui/forms/validation/validators/validators.ts
> Fix validator

- src/pages/project/EditProjectPage.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-772
Ссылка на скрипт: http://VEGA-772.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-772
> VEGA-772: Исправить сброс данных на форме редактирования при ошибке об неуникальном наименовании

- src/ui/features/projects/ProjectForm/Banner.tsx
- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-781
Ссылка на скрипт: http://VEGA-781.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-781
> VEGA-781: [В МАСТЕР] Убрать пункт «Не выбрано» в комбобоксе «Регион»

- src/pages/project/EditProjectPage.tsx
- src/pages/projects/ProjectsPage.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-786
Ссылка на скрипт: http://VEGA-786.vega-sp.csssr.cloud/vega-sp.js
Задача на бэк: https://jira.konakov.tv/browse/VEGA-2144
ПР на бэк: https://git.konakov.tv/vega2/vega2-back-core/-/merge_requests/111
> VEGA-786: Исправить ts типы проекта

- src/pages/project/CreateProjectPage.tsx
- src/pages/project/EditProjectPage.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-790
Ссылка на скрипт: http://VEGA-790.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-790
https://jira.konakov.tv/browse/VEGA-2883
> VEGA-790: Убрать проверку на наличие ошибки в поле года начала планирования 

- codegen.yml
- package.json
- src/pages/project/CreateProjectPage.tsx
- src/pages/project/ProjectPage.css
- src/pages/project/RouteLeavingGuard.tsx
- src/pages/project/project.graphql
- src/pages/projects/ProjectsPage.css
- src/pages/projects/ProjectsPage.tsx
- src/ui/features/projects/ProjectForm/Footer.tsx
- src/ui/features/projects/ProjectForm/ProjectForm.tsx
- src/ui/features/projects/ProjectForm/types.ts
- yarn.lock
Задача в Jira CSSSR: 
- https://jira.csssr.io/browse/VEGA-710
- https://jira.csssr.io/browse/VEGA-747
Ссылка на скрипт: http://VEGA-710.vega-sp.csssr.cloud/vega-sp.js
> VEGA-710: Создание проекта. Работа с blank - сохранение полей налету

- src/ui/features/projects/ProjectForm/ProjectForm.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-796
Ссылка на скрипт: http://VEGA-796.vega-sp.csssr.cloud/vega-sp.js
> VEGA-796: Восстановить создание проекта

- package.json
- src/pages/project/EditProjectPage.tsx
- src/pages/projects/ProjectsPage.tsx
- src/pages/projects/ProjectsPageView.tsx
- src/pages/projects/ProjectsTable/EditedAt/EditedAt.tsx
- src/pages/projects/ProjectsTable/ProjectsTable.tsx
- yarn.lock
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-691
Ссылка на скрипт: http://VEGA-691.vega-sp.csssr.cloud/vega-sp.js
> VEGA-691: Добавить data-test-id для страницы списка проектов

- src/pages/project/CreateProjectPage.tsx
- src/ui/features/projects/ProjectForm/Banner.tsx
- src/ui/features/projects/ProjectForm/Footer.tsx
- src/ui/features/projects/ProjectForm/ProjectForm.tsx
- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
- src/ui/features/projects/ProjectForm/steps/DocumentStep/SidebarForm/SidebarItem.tsx
- src/ui/features/projects/ProjectForm/steps/ParticipantStep/ParticipantForm/ParticipantForm.tsx
- src/ui/features/projects/ProjectForm/steps/ParticipantStep/ParticipantStep.tsx
здесь же https://jira.csssr.io/browse/VEGA-693
> VEGA-692: Добавить data-test-id для страницы создания проекта

- src/ui/features/projects/ProjectForm/ProjectForm.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-777
Ссылка на скрипт: http://VEGA-777.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-777
> VEGA-777: Реализовать фокус при ошибках на форме создания / редактирования проекта

- .github/workflows/build-static.yaml
- .github/workflows/continuous-integration.yml
- .gitignore
- codegen.yml
- graphql.schema.json
- schema.graphql
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-773
Ссылка на скрипт: http://VEGA-773.vega-sp.csssr.cloud/vega-sp.js
> VEGA-773: Разобраться с генерацией схемы

- graphql.schema.json
- src/pages/projects/ProjectsPage.tsx
- src/pages/projects/ProjectsTable/EditedAt/EditedAt.tsx
- src/pages/projects/ProjectsTable/EditedAt/cn-edited-at.ts
- src/pages/projects/ProjectsTable/ProjectsTable.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-639
Ссылка на скрипт: http://VEGA-639.vega-sp.csssr.cloud/vega-sp.js
- изменена логика отображения кнопки меню
- добавлено активное состояние для строки таблицы при открытом меню
> VEGA-639: Изменить поведение таблицы при открытом выпадающем меню

- src/pages/projects/ProjectsTable/ProjectsTable.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-830
Ссылка на скрипт: http://VEGA-830.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-830
> VEGA-830: Разделить data-test-id для кнопки Избранное

- src/ui/features/projects/ProjectForm/steps/DocumentStep/SidebarForm/utils.ts
- src/utils/getPluralForm/getPluralForm.test.tsx
- src/utils/getPluralForm/index.ts
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-368
Ссылка на скрипт: http://VEGA-368.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-368
> VEGA-368: Доработать утилиту getPluralForm

- graphql.schema.json
- src/pages/project/CreateProjectPage.tsx
- src/pages/project/EditProjectPage.tsx
- src/ui/features/projects/ProjectForm/Footer.tsx
- src/ui/features/projects/ProjectForm/types.ts
Задача в Jira CSSSR: 
- https://jira.csssr.io/browse/VEGA-791
- https://jira.csssr.io/browse/VEGA-793
Ссылка на скрипт: http://VEGA-791.vega-sp.csssr.cloud/vega-sp.js
> VEGA-791: Исправить поведение футера на странице редактирования проекта при ошибке от бэка

- graphql.schema.json
- src/ui/features/projects/ProjectForm/ProjectForm.tsx
- src/utils/debounce/debounce.test.ts
- src/utils/debounce/debounce.ts
- src/utils/debounce/index.ts
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-794
Ссылка на скрипт: http://VEGA-794.vega-sp.csssr.cloud/vega-sp.js
> VEGA-794: Заменить событие автосохранения полей черновика

- .github/workflows/coverage.yml
- jest.config.js
- package.json
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-804
Ссылка на скрипт: http://VEGA-804.vega-sp.csssr.cloud/vega-sp.js
> VEGA-804: Настроить test coverage для vega-sp

- .github/workflows/coverage.yml
- schema.graphql
- src/pages/project/CreateProjectPage.tsx
- src/pages/project/EditProjectPage.tsx
- src/pages/project/project.graphql
- src/pages/projects/ProjectsPage.tsx
- src/pages/projects/projects.graphql
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-821
Ссылка на скрипт: http://VEGA-821.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-821
> VEGA-821: Убрать поле localProject из UpdateProjectDiff

- src/pages/project/EditProjectPage.tsx
- src/ui/features/projects/ProjectForm/Footer.tsx
Jira issue: VEGA-847
https://jira.csssr.io/browse/VEGA-847
> VEGA-847: Восстановить подгрузку новой версии проекта при отмене изменений в одной из вкладок

- graphql.schema.json
- package.json
- src/ui/features/projects/ProjectForm/steps/ParticipantStep/ParticipantForm/ParticipantForm.tsx
- types/notifications.d.ts
- yarn.lock
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-852
Ссылка на скрипт: http://VEGA-852.vega-sp.csssr.cloud/vega-sp.js
> VEGA-852: Исправить баг с отображением опций Combobox

- src/App/App.tsx
- src/App/index.tsx
- src/pages/project/CreateProjectPage.tsx
- src/providers/bus/Bus.tsx
- src/providers/bus/index.ts
- src/providers/index.ts
- types/bus.d.ts
Задача в Jira CSSSR: 
- https://jira.csssr.io/browse/VEGA-798
- https://jira.csssr.io/browse/VEGA-844
Ссылка на скрипт: http://VEGA-798.vega-sp.csssr.cloud/vega-sp.js
> VEGA-798: Синхронизировать редиректы при создании и отмене проекта в нескольких вкладках

- graphql.schema.json
- src/pages/projects/ProjectsTable/ProjectsTable.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-857
Ссылка на скрипт: http://VEGA-857.vega-sp.csssr.cloud/vega-sp.js
> VEGA-857: Исправить переход на страницу проекта по нажатию на строку в таблице

- src/ui/core/TextField/TextField.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-823
Ссылка на скрипт: http://VEGA-823.vega-sp.csssr.cloud/vega-sp.js
> VEGA-823: Восстановить отображение валидации полей

- src/pages/project/EditProjectPage.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-855
Ссылка на скрипт: http://VEGA-855.vega-sp.csssr.cloud/vega-sp.js
…роекта
Jira issue: VEGA-855
> VEGA-855: Исправить поведение валидации при отмене изменений

- src/pages/project/CreateProjectPage.tsx
- src/ui/core/TextField/TextField.tsx
- src/ui/features/projects/ProjectForm/ProjectForm.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-860
Ссылка на скрипт: http://VEGA-860.vega-sp.csssr.cloud/vega-sp.js
> VEGA-860: Реализовать отображение валидации при смене фокуса и по нажатию кнопки сабмита

- src/pages/projects/ProjectsTable/EditedAt/EditedAt.css
- src/pages/projects/ProjectsTable/EditedAt/EditedAt.tsx
- src/pages/projects/ProjectsTable/ProjectsTable.css
- src/pages/projects/ProjectsTable/ProjectsTable.tsx
Задача в Jira CSSSR:
- https://jira.csssr.io/browse/VEGA-827
- https://jira.csssr.io/browse/VEGA-788
Ссылка на скрипт: http://VEGA-827.vega-sp.csssr.cloud/vega-sp.js
> VEGA-827: Исправить поведение кнопки Добавить в избранное при открытом меню

- graphql.schema.json
- src/ui/features/projects/ProjectForm/ProjectForm.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-894
Ссылка на скрипт: http://VEGA-894.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-894
> VEGA-894: Исправить ошибку 400 при обновлении черновика проекта

- graphql.schema.json
- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
Jira issue: [VEGA-895](https://jira.csssr.io/browse/VEGA-895)
> VEGA-895: Исправить поведение футера на странице редактирования проекта при сохранении года начала планирования

- .gitignore
- jest.config.js
- package.json
- src/pages/projects/ModalDeleteProject/ModalDeleteProject.tsx
- src/pages/projects/ModalDeleteProject/index.ts
- src/pages/projects/ProjectsPage.css
- src/pages/projects/ProjectsPage.test.tsx
- src/pages/projects/ProjectsPage.tsx
- src/pages/projects/ProjectsPageView.test.tsx
- src/pages/projects/ProjectsPageView.tsx
- src/pages/projects/ProjectsTable/EditedAt/EditedAt.css
- src/pages/projects/ProjectsTable/EditedAt/EditedAt.test.tsx
- src/pages/projects/ProjectsTable/EditedAt/EditedAt.tsx
- src/pages/projects/ProjectsTable/ProjectsTable.test.tsx
- src/pages/projects/ProjectsTable/ProjectsTable.tsx
- src/pages/projects/ProjectsTable/types.ts
- src/pages/projects/__mocks__/mock-default.ts
- src/pages/projects/__mocks__/mock-delete-project.ts
- src/pages/projects/__mocks__/mock-favorite-project.ts
- src/pages/projects/__mocks__/mocks.ts
- src/pages/projects/projects.graphql
- src/utils/projects-mapper/index.ts
- src/utils/projects-mapper/projects-mapper.test.ts
- src/utils/projects-mapper/projects-mapper.ts
- test-utils/index.ts
- test-utils/mount-app.tsx
- yarn.lock
создал задачу на недостающие тесты https://jira.csssr.io/browse/VEGA-849
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-813
Ссылка на скрипт: http://VEGA-813.vega-sp.csssr.cloud/vega-sp.js
> VEGA-813: Покрыть тестами список проектов

- graphql.schema.json
- src/pages/project/CreateProjectPage.tsx
- src/pages/project/EditProjectPage.tsx
- src/pages/project/extract-project-validation-errors.ts
- src/pages/project/project.graphql
Задача в Jira VEGA: https://jira.konakov.tv/browse/VEGA-482
Ссылка на скрипт: http://VEGA-482.vega-sp.csssr.cloud/vega-sp.js
MR BE https://git.konakov.tv/vega2/vega2-back-core/-/merge_requests/323
Измененный формат валидации - включает в себя новый тип ошибки ValidationError с набором ValidationErrorItem где указывается path, code, message для определения поля, типа ошибки валидации (ValidationErrorCode) и сообщения если оно есть.
> [VEGA-482]: refactor(validation): обновление валидации

- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-892
Ссылка на скрипт: http://VEGA-892.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-892
> VEGA-892: Изменить плейсхолдер в поле Название проекта

- src/pages/project/CreateProjectPage.tsx
- src/pages/project/EditProjectPage.tsx
- src/ui/features/projects/ProjectForm/ProjectForm.tsx
- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-792
Ссылка на скрипт: http://VEGA-792.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-792
> VEGA-792: Восстановить трим пробелов

- src/ui/features/projects/ProjectForm/ProjectForm.test.tsx
- src/ui/features/projects/ProjectForm/ProjectForm.tsx
- src/ui/features/projects/ProjectForm/steps/DescriptionStep/DescriptionStep.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-929
Ссылка на скрипт: http://VEGA-929.vega-sp.csssr.cloud/vega-sp.js
> VEGA-929: Восстановить удаление региона при редактировании проекта и создании черновика

- .gitignore
- src/hooks/use-browser-tab-activity.test.tsx
- src/pages/project/CreateProjectPage.test.tsx
- src/pages/project/CreateProjectPage.tsx
- src/pages/projects/ProjectsFilter/ProjectsFilter.test.tsx
- src/pages/projects/ProjectsFilter/ProjectsFilter.tsx
- src/pages/projects/ProjectsPage.test.tsx
- src/pages/projects/ProjectsPage.tsx
- src/pages/projects/ProjectsPageView.test.tsx
- src/pages/projects/ProjectsTable/EditedAt/EditedAt.test.tsx
- src/pages/projects/ProjectsTable/EditedAt/EditedAt.tsx
- src/pages/projects/ProjectsTable/ProjectsTable.test.tsx
- src/pages/projects/ProjectsTable/ProjectsTable.tsx
- src/pages/projects/__mocks__/mock-default.ts
- src/pages/projects/__mocks__/mock-delete-project.ts
- src/pages/projects/__mocks__/mock-favorite-project-error.ts
- src/pages/projects/__mocks__/mock-favorite-project.ts
- src/pages/projects/__mocks__/mock-paginations.ts
- src/pages/projects/__mocks__/mock-refetch.ts
- src/pages/projects/__mocks__/mocks.ts
- src/providers/notifications/Notifications.tsx
- src/utils/projects-mapper/projects-mapper.test.ts
- test-utils/change-visibility-state.ts
- test-utils/mount-app.tsx
- test-utils/notificationsMock.ts
- types/notifications.d.ts
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-858
Ссылка на скрипт: http://VEGA-858.vega-sp.csssr.cloud/vega-sp.js
> VEGA-858: Доработать обёртку для тестирования компонентов

- codegen.yml
- graphql.schema.json
- package.json
- schema.graphql
- src/pages/project/CreateProjectPage.tsx
- src/pages/projects/ProjectsPage.tsx
- src/pages/projects/__mocks__/mock-favorite-project-error.ts
- src/pages/projects/__mocks__/mock-favorite-project.ts
- src/pages/projects/projects.graphql
- yarn.lock
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-936
Ссылка на скрипт: http://VEGA-936.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-936
> VEGA-936: Изменить добавление проекта в избранное в соответствии с новым бэком

- graphql.schema.json
- schema.graphql
- src/pages/project/CreateProjectPage.test.tsx
- src/pages/project/CreateProjectPage.tsx
- src/pages/project/project.graphql
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-931
Ссылка на скрипт: http://VEGA-931.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-931
> VEGA-931: Изменить создание проекта в соответствии с новым бэкендом

- package.json
- src/pages/project/RouteLeavingGuard.tsx
- src/pages/projects/ModalDeleteProject/ModalDeleteProject.tsx
- src/pages/projects/ProjectsPage.test.tsx
- src/ui/features/projects/ProjectForm/steps/DocumentStep/SidebarForm/SidebarForm.tsx
- yarn.lock
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-906
Ссылка на скрипт: http://VEGA-906.vega-sp.csssr.cloud/vega-sp.js
> VEGA-906: Добавить data-testid для подтверждения об отмене создания проекта

- src/pages/project/CreateProjectPage.tsx
- src/pages/project/RouteLeavingGuard.tsx
- src/ui/features/projects/ProjectForm/Autosave.tsx
- src/ui/features/projects/ProjectForm/ProjectForm.test.tsx
- src/ui/features/projects/ProjectForm/ProjectForm.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-901
Ссылка на скрипт: http://VEGA-901.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-901
> VEGA-901: Рефакторинг автосейва в ProjectForm

- graphql.schema.json
- schema.graphql
- src/pages/project/CreateProjectPage.test.tsx
- src/ui/features/projects/ProjectForm/ProjectForm.test.tsx
- src/ui/features/projects/ProjectForm/ProjectForm.tsx
- src/ui/features/projects/ProjectForm/__tests__/utils.ts
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-923
Ссылка на скрипт: http://VEGA-923.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-923
> VEGA-923: Покрыть тестами валидацию в ProjectForm

- src/pages/projects/ProjectsTable/ProjectsTable.test.tsx
- src/pages/projects/ProjectsTable/ProjectsTable.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-928
Ссылка на скрипт: http://VEGA-928.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-928
> VEGA-928: Исправить анимацию при вызове меню у удаленного проекта

- ci/build.sh
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-3243
Ссылка на скрипт: http://VEGA-3243.vega-sp.csssr.cloud/vega-sp.js
https://jira.vegaspace.tk/browse/VEGA-3243
- игнор ошибок удаления докер контейнера
https://git.konakov.tv/vega2/vega-builder-automation/-/merge_requests/61
> [VEGA-3243] ci: Исправление общего механизма сборки YC

- .eslintignore
- .github/workflows/build-static.yaml
- .github/workflows/continuous-integration.yml
- .github/workflows/coverage.yml
- .graphqlconfig
- .graphqlrc.yaml
- .prettierignore
- codegen.yml
- package.json
- yarn.lock
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-971
Ссылка на скрипт: http://VEGA-971.vega-sp.csssr.cloud/vega-sp.js
Jira issue: VEGA-971
> VEGA-971: Убрать graphql.schema.json из реп

- src/pages/project/EditProjectPage.test.tsx
- test-utils/mount-app.tsx
Задача в Jira CSSSR: https://jira.csssr.io/browse/VEGA-816
Ссылка на скрипт: http://VEGA-816.vega-sp.csssr.cloud/vega-sp.js
> VEGA-816: Покрыть тестами редактирование проекта

- ci/build-entrypoint.sh
- ci/build.sh
Задача в Jira GPN: https://jira.konakov.tv/browse/VEGA-3243
https://jira.vegaspace.tk/browse/VEGA-3243
Добавление параметров, необходимых для сборки на YC
> [VEGA-3243] ci: add BASE_URL variable to docker

- schema.graphql
- src/App/AppView.test.tsx
- src/pages/projects/ProjectsPage.test.tsx
- src/pages/projects/ProjectsPage.tsx
- src/pages/projects/ProjectsPageView.test.tsx
- src/pages/projects/ProjectsPageView.tsx
- src/pages/projects/ProjectsTable/ProjectsTable.tsx
- src/pages/projects/ProjectsTable/types.ts
- src/pages/projects/__mocks__/mock-default.ts
- src/pages/projects/__mocks__/mock-delete-project.ts
- src/pages/projects/__mocks__/mock-favorite-project-error.ts
- src/pages/projects/__mocks__/mock-favorite-project.ts
- src/pages/projects/__mocks__/mock-paginations.ts
- src/pages/projects/projects.graphql
Задача в Jira GPN: https://jira.konakov.tv/browse/VEGA-3434
> VEGA-3434: Добавление сортировки списка проектов

- jest.config.js
- package.json
- yarn.lock
> Added jest-junit reporter

- package.json
- yarn.lock
_{Jira issue number, description or crucial excerpts}_
_{What has been done (list of details)}_
_{Jira issues or PRs related to this one}_
```
$export NODE_ENV="production"
$yarn install --production=true
$yarn build
```
> chore(global):upd deps webpackDev moved to devDeps
